# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/analog/workspace/practica/hdl/projects/ad5592r_pmdz/coraz7s/ad5592r_coraz7s.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
# IP: The module: 'system_sys_rstgen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/analog/workspace/practica/hdl/projects/ad5592r_pmdz/coraz7s/ad5592r_coraz7s.gen/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_rstgen_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/analog/workspace/practica/hdl/projects/ad5592r_pmdz/coraz7s/ad5592r_coraz7s.gen/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_rstgen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/analog/workspace/practica/hdl/projects/ad5592r_pmdz/coraz7s/ad5592r_coraz7s.gen/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_rstgen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/analog/workspace/practica/hdl/projects/ad5592r_pmdz/coraz7s/ad5592r_coraz7s.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
# IP: The module: 'system_sys_rstgen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/analog/workspace/practica/hdl/projects/ad5592r_pmdz/coraz7s/ad5592r_coraz7s.gen/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_rstgen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/analog/workspace/practica/hdl/projects/ad5592r_pmdz/coraz7s/ad5592r_coraz7s.gen/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_rstgen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/analog/workspace/practica/hdl/projects/ad5592r_pmdz/coraz7s/ad5592r_coraz7s.gen/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_rstgen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
