
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: eyeBrows
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_eyeBrows[21] = {
    // ∙∙∙∙∙█████████∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙█████████∙∙∙∙∙
    // ∙∙███∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙███∙∙
    // ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██
    0x07, 0xfc, 0x00, 0x00, 0x0f, 0xf8, 0x00, 
    0x38, 0x03, 0xc0, 0x00, 0xf0, 0x07, 0x00, 
    0xc0, 0x00, 0x30, 0x03, 0x00, 0x00, 0xc0
};
const tImage eyeBrows = { image_data_eyeBrows, 50, 3,
    8 };

